alter table public.feedback_messages
add column if not exists submission_data jsonb;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (char_length(event_name) between 1 and 64),
  event_value integer not null default 1 check (event_value >= 0),
  visitor_id text not null check (char_length(visitor_id) between 8 and 100),
  session_id text not null check (char_length(session_id) between 8 and 100),
  user_id uuid references auth.users(id) on delete set null,
  path text,
  country text not null default 'XX' check (char_length(country) = 2),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.analytics_events enable row level security;
grant insert on public.analytics_events to anon, authenticated;
grant select on public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "Anyone can record analytics" on public.analytics_events;
create policy "Anyone can record analytics"
on public.analytics_events for insert to anon, authenticated
with check (true);

drop policy if exists "Developer can read analytics" on public.analytics_events;
create policy "Developer can read analytics"
on public.analytics_events for select to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'majurx64@yandex.ru');

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_name_created_idx on public.analytics_events (event_name, created_at desc);
create index if not exists analytics_events_visitor_created_idx on public.analytics_events (visitor_id, created_at desc);

create or replace function public.analytics_dashboard(period_days integer default 30)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
  safe_days integer := greatest(1, least(coalesce(period_days, 30), 365));
begin
  if lower(coalesce(auth.jwt() ->> 'email', '')) <> 'majurx64@yandex.ru' then
    raise exception 'not allowed';
  end if;

  with scoped as (
    select * from public.analytics_events
    where created_at >= now() - make_interval(days => safe_days)
  ), summary as (
    select
      count(*) filter (where event_name = 'page_view') as page_views,
      count(distinct visitor_id) as unique_visitors,
      count(distinct session_id) as sessions,
      count(distinct user_id) filter (where user_id is not null) as authenticated_users,
      coalesce(sum(event_value) filter (where event_name = 'active_seconds'), 0) as active_seconds,
      coalesce(sum(event_value) filter (where event_name = 'map_created'), 0) as maps_created,
      coalesce(sum(event_value) filter (where event_name = 'map_deleted'), 0) as maps_deleted,
      coalesce(sum(event_value) filter (where event_name = 'cells_created'), 0) as cells_created,
      coalesce(sum(event_value) filter (where event_name = 'cells_painted'), 0) as cells_painted,
      coalesce(sum(event_value) filter (where event_name = 'cells_erased'), 0) as cells_erased,
      coalesce(sum(event_value) filter (where event_name = 'feedback_sent'), 0) as feedback_sent,
      coalesce(sum(event_value) filter (where event_name = 'library_submission'), 0) as library_submissions
    from scoped
  ), daily as (
    select jsonb_agg(row_data order by day) as data from (
      select created_at::date as day,
        count(*) filter (where event_name = 'page_view') as views,
        count(distinct visitor_id) as visitors,
        coalesce(sum(event_value) filter (where event_name = 'maps_created'), 0) as maps,
        coalesce(sum(event_value) filter (where event_name = 'cells_painted'), 0) as painted
      from scoped group by created_at::date
    ) row_data
  ), countries as (
    select jsonb_agg(row_data order by visitors desc) as data from (
      select country, count(distinct visitor_id) as visitors, count(*) filter (where event_name = 'page_view') as views
      from scoped group by country
    ) row_data
  ), screens as (
    select jsonb_agg(row_data order by views desc) as data from (
      select coalesce(metadata ->> 'screen', 'unknown') as screen, count(*) as views
      from scoped where event_name = 'page_view' group by metadata ->> 'screen'
    ) row_data
  )
  select jsonb_build_object(
    'period_days', safe_days,
    'summary', to_jsonb(summary),
    'daily', coalesce(daily.data, '[]'::jsonb),
    'countries', coalesce(countries.data, '[]'::jsonb),
    'screens', coalesce(screens.data, '[]'::jsonb)
  ) into result from summary cross join daily cross join countries cross join screens;
  return result;
end;
$$;

revoke all on function public.analytics_dashboard(integer) from public;
grant execute on function public.analytics_dashboard(integer) to authenticated;
